/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Report5.ac.uryukyu.ie.e235756;

import org.junit.jupiter.api.Test;

import Report5.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
